var DIR, du, fs, path, total_bytes, total_kb, total_mb;

fs = require('fs');
path = require('path');

du = function(dir) {
  var e, file, files, i, len, stat, total;
  total = 0;
  try {
    stat = fs.lstatSync(dir);
    if (stat.isFile()) {
      total += stat.size;
    } else if (stat.isDirectory()) {
      files = fs.readdirSync(dir);
      for (i = 0, len = files.length; i < len; i++) {
        file = files[i];
        total += du(path.join(dir, file));
      }
    }
  } catch (_error) {
    e = _error;
  }
  return total;
};

DIR = './assets/branding';

total_bytes = du(DIR);

total_kb = total_bytes / 1024.0;

total_mb = total_kb / 1024.0;

console.log(DIR + ": " + (total_mb.toFixed(3)) + " MB");

// ---
// generated by coffee-script 1.9.2